---
- name: installing requirements
  hosts: localhost
  connection: local

  tasks:
  - name: latest nitrogen
    become: yes
    become_user: root
    pacman:
      name: nitrogen
      state: latest
  - name: latest rofi
    become: yes
    become_user: root
    pacman:
      name: rofi
      state: latest
  - name: latest autorandr
    become: yes
    become_user: root
    pacman:
      name: autorandr
      state: latest
  - name: latest fish
    become: yes
    become_user: root
    pacman:
      name: fish
      state: latest
  - name: latest archlinux-wallpaper
    become: yes
    become_user: root
    pacman:
      name: archlinux-wallpaper
      state: latest

  - name: Ensure qtile config dir
    file:
      path: ~/.config/qtile
      state: directory
  - name: Ensure nitrogen config dir
    file:
      path: ~/.config/nitrogen
      state: directory

  - name: qtile config
    template:
      src: templates/qtile/config.py
      dest: ~/.config/qtile/config.py
  - name: qtile autostart
    template:
      src: templates/qtile/autorun.sh
      dest: ~/.config/qtile/autorun.sh
      mode: u+rwx
  - name: nitrogen configuration
    template:
      src: templates/nitrogen/nitrogen.cfg
      dest: ~/.config/nitrogen/nitrogen.cfg
  - name: nitrogen current wallpaper configuration
    template:
      src: templates/nitrogen/bg-saved.cfg
      dest: ~/.config/nitrogen/bg-saved.cfg

  - name: quit qtile
    shell: ps x | grep "qtile" | head -n1 | awk '{print $1}' | xargs kill

