---
- name: QTile for Arch Linux
  hosts: localhost
  connection: local
  tasks:
  - import_tasks: tasks/requirements.yml
    become: yes
  - import_tasks: tasks/qtile.yml
  - import_tasks: tasks/nitrogen.yml
  - import_tasks: tasks/x11.yml
  - import_tasks: tasks/picom.yml

# poetry completions bash > /etc/bash_completion.d/poetry.bash-completion
