---
- name: QTile for Arch Linux
  hosts: localhost
  connection: local
  tasks:
    name: Requirements
    become: yes
      - include_tasks: tasks/requirements.yml
    - include_tasks: tasks/qtile.yml
    - include_tasks: tasks/nitrogen.yml
    - include_tasks: tasks/x11.yml

