---
- name: synchronize pacman
  pacman:
    update_cache: yes

- name: latest nitrogen
  pacman:
    name: nitrogen
    state: latest

- name: latest rofi
  pacman:
    name: rofi
    state: latest

- name: latest autorandr
  pacman:
    name: autorandr
    state: latest

- name: latest fish
  pacman:
    name: fish
    state: latest

- name: latest man
  pacman:
    name: man
    state: latest

- name: latest man-db
  pacman:
    name: man-db
    state: latest

- name: latest archlinux-wallpaper
  pacman:
    name: archlinux-wallpaper
    state: latest
