
---
- name: X11 Automatic resolution restoration
  template:
    src: templates/X11/.xprofile
    dest: ~/.xprofile

- name: X11 Automatic resolution restoration
  become: yes
  template:
    src: templates/X11/.xprofile
    dest: /root/.xprofile
    owner: root
    group: root
